const data = [
  {
    id: 1,
    image: 'longLogo.png',
    name: 'Apexion Team',
    description: '代表色：黑色',
    description2: 'Based in Taiwan',
    description3: 'Established in 2022',
    level: '團隊成員:7人',
  },
  {
    id: 2,
    image: 'member1.png',
    name: 'Amanda',
    description: '代表色：銀色',
    description2: '里程數：2500km',
    description3: '負責：首頁＆論壇',
    level: ' LEVEL - 5',
  },
  {
    id: 3,
    image: 'member2.png',
    name: 'Tina',
    description: '代表色：金色',
    description2: '里程數：2550km',
    description3: '負責：訂票頁面',
    level: ' LEVEL - 5',
  },
  {
    id: 4,
    image: 'member3.png',
    name: 'Ting',
    level: ' LEVEL - 5',
    description: '代表色：藍色',
    description2: '里程數：2500km',
    description3: '負責：商品頁',
  },
  {
    id: 5,
    image: 'member4.png',
    name: 'Sam',
    level: ' LEVEL - 5',
    description: '代表色：螢光',
    description2: '里程數：2450km',
    description3: '負責：會員頁',
  },
  {
    id: 6,
    image: 'member5.png',
    name: 'Michael',
    level: ' LEVEL - 5',
    description: '代表色：亮藍色',
    description2: '里程數：2550km',
    description3: '負責：客製化商品',
  },
  {
    id: 7,
    image: 'member6.png',
    name: 'Troy',
    level: ' LEVEL - 5',
    description: '代表色：橘色',
    description2: '里程數：2570km',
    description3: '負責：行程頁',
  },
  {
    id: 8,
    image: 'member7.png',
    name: 'Albert',
    level: ' LEVEL - 5',
    description: '代表色：霓虹',
    description2: '里程數：2500km',
    description3: '負責：購物車',
  },
];
export { data };
