const TestData = [
  {
    mtl_id: 13,
    mtl_sugar: 0,
    mtl_oil: 2,
    mtl_protein: 30,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 30,
  },
  {
    mtl_id: 15,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 32,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 20,
  },
  {
    mtl_id: 16,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 29,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 20,
  },
  {
    mtl_id: 13,
    mtl_sugar: 0,
    mtl_oil: 2,
    mtl_protein: 30,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 30,
  },
  {
    mtl_id: 14,
    mtl_sugar: 0,
    mtl_oil: 3,
    mtl_protein: 15,
    mtl_carbo: 0,
    mtl_na: 1,
    mtl_calories: 20,
  },
  {
    mtl_id: 15,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 32,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 20,
  },
  {
    mtl_id: 1,
    mtl_sugar: 3,
    mtl_oil: 0,
    mtl_protein: 20,
    mtl_carbo: 20,
    mtl_na: 0,
    mtl_calories: 25,
  },
  {
    mtl_id: 3,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 31,
    mtl_carbo: 0,
    mtl_na: 1,
    mtl_calories: 20,
  },
  {
    mtl_id: 4,
    mtl_sugar: 0,
    mtl_oil: 2,
    mtl_protein: 29,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 20,
  },
  {
    mtl_id: 34,
    mtl_sugar: 0,
    mtl_oil: 0,
    mtl_protein: 5,
    mtl_carbo: 5,
    mtl_na: 1,
    mtl_calories: 20,
  },
  {
    mtl_id: 35,
    mtl_sugar: 0,
    mtl_oil: 0,
    mtl_protein: 0,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 20,
  },
  {
    mtl_id: 36,
    mtl_sugar: 0,
    mtl_oil: 2,
    mtl_protein: 15,
    mtl_carbo: 15,
    mtl_na: 0,
    mtl_calories: 20,
  },
  {
    mtl_id: 8,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 15,
    mtl_carbo: 0,
    mtl_na: 0,
    mtl_calories: 10,
  },
  {
    mtl_id: 9,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 15,
    mtl_carbo: 0,
    mtl_na: 1,
    mtl_calories: 12,
  },
  {
    mtl_id: 10,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 29,
    mtl_carbo: 0,
    mtl_na: 1,
    mtl_calories: 15,
  },
  {
    mtl_id: 1,
    mtl_sugar: 3,
    mtl_oil: 0,
    mtl_protein: 20,
    mtl_carbo: 20,
    mtl_na: 0,
    mtl_calories: 25,
  },
  {
    mtl_id: 2,
    mtl_sugar: 0,
    mtl_oil: 3,
    mtl_protein: 30,
    mtl_carbo: 0,
    mtl_na: 1,
    mtl_calories: 25,
  },
  {
    mtl_id: 3,
    mtl_sugar: 0,
    mtl_oil: 1,
    mtl_protein: 31,
    mtl_carbo: 0,
    mtl_na: 1,
    mtl_calories: 20,
  },
];
export { TestData };
